# Generated by Django 3.2.9 on 2022-02-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='paragraths',
            field=models.TextField(max_length=100),
        ),
    ]
