# Generated by Django 2.2.7 on 2022-02-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_paragraths_poem_paragraphs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
