# Generated by Django 3.2.12 on 2022-02-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20220217_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
